## 코틀린에서 예외를 다루는 방법
### try catch finally
```kotlin
fun parseIntOrThrow(str: String): Int {
    try {
        return str.toInt()
    } catch(e: NumberFormatException) {
        throw IllegalArgumentException("주어진 ${str}는 숫자가 아닙니다.")
    }
}
```
* 타입이 뒤에 위치
* new 를 사용하지 않음
* format 이 간단함
* 즉, 그 외는 자바와 동일

```kotlin
fun parseIntOrThrowV2(str: String): Int? {
    return try {
        str.toInt()
    } catch (e: NumberFormatException) {
        null
    }
}
```
* kotlin 의 try catch 도 expression 으로 취급할 수 있기 때문에 위처럼 변경할 수 있다.

### checked exception and unchecked exception
```kotlin
fun readFile() { 
    val currentFile = File(".") 
    val file = File(currentFile.absolutePath + "/a.txt") 
    val reader = BufferedReader(FileReader(file))
    println(reader.readLine())
    reader.close()
}
```
* Java 에서는 위 코드를 작성 시 File 관련 코드 때문에 IOException 을 넣어줘야한다.
* 하지만, 코틀린은 빨간줄도 안뜨고 경고표시도 안해준다. 
* 코틀린은 throws 구문이 없다. 즉, ```public void func() throws IOException { ... }``` 와 같은 구문이 없다.
* 코틀린은 checked exception 과 unchecked exception 구분하지 않는다. 모두 unchecked exception 으로 간주한다.

### try with resources
```java
public class JavaFilePrinter {
    public void readFile(String path) throws IOException {
        try (BufferedReader reader = new BufferedReader(new FileReader(path))) {
            System.out.println(reader.readLine());
        }
    }
}
```
* 위 자바의 try with resources 구문은 JDK7에 추가되었다.
```kotlin
fun readFile(path: String) {
    BufferedReader(FileReader(path)).use { reader ->
        println(reader.readLine())
    }
}
```
* 코틀린에서는 try with resources 가 사라지고 use 라는 inline 확장함수를 사용한다. (나중에 자세히 설명)